### ISSUE TITLE
DB Todo-List Ideensammlung

### ISSUE THREAD

**Issue by reuschem** [medizininformatik-initiative/INTERPOLAR#284]
- [x]  auf eine einzelne Sequenz umstellen --> Historie
- [x] Zählen der Gefundenen / Updatet und Kopierten Datensätze beim verschieben der Daten
- [ ] View um Datenfluss von Insert bis Frontend nachzuverfolgen
- [x] Funktion um DB Struktur Änderungen zu dokumentieren (nth)
- [x] Protokollierung von Datenimports - evtl. als Ergebnis aus der Zählung der Datensätze
- [x] Parameter (FHIR_data_timeaccuracy, Interval_data_import_in_hour, Interval_data_processing, ....)
- [ ] Statistiktabellen mit Entwickeln und im Kern zur Verfügung stellen
- [ ] Für laufende Tests im Betrieb die Frontend Tabellen überprüfen ob (bei nicht Verwendung unseres Projektes) verschiedene Forms_Name verwendet werden

**Comment by reuschem** [comment]
- Zählen der Gefundenen / Updatet und Kopierten Datensätze beim verschieben der Daten -> in branch #471 mit bearbeitet
- Protokollierung von Datenimports - evtl. als Ergebnis aus der Zählung der Datensätze -> in branch #471 mit bearbeitet

**Comment by SebStaeubert** [comment]
Durch Reporting abgedeckt.
